# https://github.com/francma/wob/blob/master/wob.ini.5.scd
timeout = 500
max = 100
width = 400
height = 20

# внешний отступ
border_offset = 0

# рамка
border_size = 5

# отступ между рамкой и полоской
bar_padding = 0

anchor = bottom center
margin = 0 0 10 0

#1D2021
border_color = 1D2021FF
#B8BB26
bar_color = B8BB26FF
#928374
background_color = 928374FF

overflow_mode = wrap
overflow_border_color = 1D2021FF
overflow_bar_color = FF0000FF
overflow_background_color = 928374FF
