bind = ALT, 6, exec, hyprctl notify -1 2000 "rgb(ff1ea3)" "Hello everyone!"
bindi = , code:201, exec, uwsm-app -- pkill -x anyrun || anyrun --plugins libapplications.so

bindeld = SUPER, F2, Volume-, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%- && echo $($getVolume) > $WOBSOCK
bindeld = SUPER, F3, Volume+, exec, bash -c 'v=$($getVolume); [[ $v -lt 150 ]] && ((v += 10)) && wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+; echo $v > $WOBSOCK'
bindld  = SUPER, F4, Microphone mute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bindd = SUPER, F9, Make Screenshot, exec, grim -g "$(slurp)" - | swappy -f -
